control_modes:
  idle: false

  teleop:
    z:        {p: 20.0,    i: 2.0 ,  d: 5.0,  pid_max: 30, pid_min: -30}
    pitch:    {p: 10.0,   i: 0.5,  d: 2.0,  pid_max: 20, pid_min: -20}


thruster_ids:

  heave_port:
    control_tf: heave_port_thruster_link
    command_topic: control/thruster/heave_port
    force_topic: control/force/heave_port
    limits: [-20.0, 20.0] #[min, max]
    delta_limit: 1.0
    polynomials: [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]

  heave_starboard:
    control_tf: heave_starboard_thruster_link
    command_topic: control/thruster/heave_starboard
    force_topic: control/force/heave_starboard
    limits: [-20.0, 20.0] #[min, max]
    delta_limit: 1.0
    polynomials: [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]
