/mini_alpha/bluerobotics_pressure_node:
    ros__parameters:
        ros:
            frame_id: 'mini_alpha/pressure'

        sensor:
            # brief: MODEL_02BA = 0, MODEL_30BA = 1
            model: 1

            # brief: Default I2C bus is 1
            bus: 1

            # brief: Fluid Density (kg/m^3); fresh: 997.0474; seawater: 1023.6
            fluid_density: 1022.0

            child_frame: 'mini_alpha/pressure'

            parent_frame: 'mini_alpha/world'

            z_covariance: 0.0

        system:
            # brief: sensor publish rate
            rate: 5