# IMPORTANT: Check v4l2-ctl --list-devices for correct ID
# exploreHD camera
/mini_alpha/exploreHD_camera_node:
  ros__parameters:
    # Video stream settings
    video:
      id: 0
      width: 640
      height: 360
      framerate: 15
      format: 'MJPG'
    # Settings for the low-bandwidth compressed stream (0 target_fps will disable this topic)
    compression:
      width: 320
      height: 240
      target_fps: 0
      jpeg_quality: 75
    # Camera hardware control settings
    camera:
      auto_exposure: True
      exposure_time: 156
      brightness: 0
      contrast: 32
      saturation: 64
      hue: 0
      gamma: 100
      gain: 0
      sharpness: 3
    ros:
      frame_id: "exploreHD_camera_frame" # Unique TF frame_id

# usbpcb camera
/mini_alpha/usbpcb_camera_node:
  ros__parameters:
    # Video stream settings
    video:
      id: 4
      width: 640
      height: 360
      framerate: 15
      format: 'MJPG'
    # Settings for the low-bandwidth compressed stream (0 target_fps will disable this topic)
    compression:
      width: 320
      height: 240
      target_fps: 0
      jpeg_quality: 75
    # Camera hardware control settings
    camera:
      auto_exposure: True
      exposure_time: 156
      brightness: 0
      contrast: 32
      saturation: 64
      hue: 0
      gamma: 100
      gain: 0
      sharpness: 3
    ros:
      frame_id: "usbpcb_camera_frame" # Unique TF frame_id