/mini_alpha/mvp_control_ros_node:
  ros__parameters:
    generator_type: tf
    controller_frequency: 10.0
    enabled: false
    child_link_initial: cg_link
    world_link_initial: world
    controller_no_setpoint_timeout: 10.0