/mini_alpha/pwm_driver_node:
  ros__parameters:
    # pwm_frequency: 47.2
    mcu_installed: true
    pwm_frequency: 47.2

    pwm_ms_bias: -0.05
    no_pwm_timeout: 10.0
  
    thruster_ch_list: [0, 1, 12, 13]
    thruster_topic_list: [control/thruster/surge_stbd, control/thruster/heave_starboard, control/thruster/heave_port, control/thruster/surge_port]
    thruster_min_us: [1100, 1100, 1100, 1100]
    thruster_max_us: [1900, 1900, 1900, 1900]
    thruster_init_us: [1500, 1500, 1500, 1500]
    thruster_direction: [1, 1, 1, 1]  #1 or -1
    
    # led_ch_list: [5]
    # led_topic_list: [led_1]
    # led_min_us: [1100]
    # led_max_us: [1900]
    # led_init_us: [1100]

    servo_ch_list: [11]
    servo_topic_list: [servo]
    servo_min_us: [600]
    servo_max_us: [1950]
    servo_center_us: [1275]
