# /mvp2_test_robot/imu_driver_node:
#     ros__parameters:
#       roll_offset: 3.1415926
#       pitch_offset: 0.0
#       yaw_offset: 1.5707
#       roll_reverse: 1.0
#       pitch_reverse: -1.0
#       yaw_reverse: -1.0

/mini_alpha/thruster_driver_node:
    ros__parameters:
      thruster_pub_topic: /mini_alpha/stonefish/thruster_command
      thruster_length: 4
      thruster_sub_topics: [/mini_alpha/control/thruster/surge_port, 
                          /mini_alpha/control/thruster/surge_stbd, 
                          /mini_alpha/control/thruster/heave_port, 
                          /mini_alpha/control/thruster/heave_stbd]

# /mvp2_test_robot/dvl_driver_node:
#     ros__parameters:
#       dvl_in: /mvp2_test_robot/dvl/stonefish/raw
#       dvl_out: /mvp2_test_robot/dvl/twist
#       dvl_alt_out: /mvp2_test_robot/dvl/altitude